### PR TITLE
update license

### PR DESCRIPTION
**Pull request by andersy005**

### CODE REVIEW

**Comment by andersy005** [comment]
the test run failure seems to be caused by some serialization issue: 


```python
    File "/usr/local/lib/python3.9/dist-packages/apache_beam/transforms/core.py", line 1877, in <lambda>
    File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pangeo_forge_recipes/executors/beam.py", line 14, in _no_arg_stage
      fun(config=config)
    File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pangeo_forge_recipes/recipes/xarray_zarr.py", line 587, in prepare_target
      for k, v in config.get_execution_context().items():
    File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pangeo_forge_recipes/recipes/base.py", line 59, in get_execution_context
      recipe_hash=self.sha256().hex(),
    File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pangeo_forge_recipes/recipes/base.py", line 53, in sha256
      return dataclass_sha256(self, ignore_keys=self._hash_exclude_)
    File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pangeo_forge_recipes/serialization.py", line 73, in dataclass_sha256
      return dict_to_sha256(d)
    File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pangeo_forge_recipes/serialization.py", line 34, in dict_to_sha256
      b = dumps(
    File "/srv/conda/envs/notebook/lib/python3.9/json/__init__.py", line 234, in dumps
      return cls(
    File "/srv/conda/envs/notebook/lib/python3.9/json/encoder.py", line 199, in encode
      chunks = self.iterencode(o, _one_shot=True)
    File "/srv/conda/envs/notebook/lib/python3.9/json/encoder.py", line 257, in iterencode
      return _iterencode(o, 0)
    File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pangeo_forge_recipes/serialization.py", line 22, in either_encode_or_hash
      return inspect.getsource(obj)
    File "/srv/conda/envs/notebook/lib/python3.9/inspect.py", line 1024, in getsource
      lines, lnum = getsourcelines(object)
    File "/srv/conda/envs/notebook/lib/python3.9/inspect.py", line 1006, in getsourcelines
      lines, lnum = findsource(object)
    File "/srv/conda/envs/notebook/lib/python3.9/inspect.py", line 827, in findsource
      raise OSError('source code not available')
  OSError: source code not available [while running 'Start|cache_input|Reshuffle_000|prepare_target|Reshuffle_001|store_chunk|Reshuffle_002|finalize_target|Reshuffle_003/prepare_target-ptransform-56']
timestamp: '2022-10-21T00:01:03.726959301Z'

````

@rabernat, Is there any chance that you may have some hints as to what's happening?

**Comment by yuvipanda** [comment]
@andersy005 YESSSS!

**Comment by andersy005** [comment]
this is huge, and will unblock plenty of recipes/feedstock! 

i'm going to merge this to see if the full recipe goes through.

**Comment by andersy005** [comment]
The full recipe worked: https://pangeo-forge.org/dashboard/feedstock/78

**Pull request merged**
